#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : httpx
Version  : 0.17.0
Release  : 8
URL      : https://files.pythonhosted.org/packages/f5/bb/136616d6a7a2e9f91d3cb65b4f0674612aea21a832c18e5efa5872d689a2/httpx-0.17.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/f5/bb/136616d6a7a2e9f91d3cb65b4f0674612aea21a832c18e5efa5872d689a2/httpx-0.17.0.tar.gz
Summary  : The next generation HTTP client.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: httpx-license = %{version}-%{release}
Requires: httpx-python = %{version}-%{release}
Requires: httpx-python3 = %{version}-%{release}
Requires: brotlipy
Requires: certifi
Requires: h2
Requires: httpcore
Requires: sniffio
BuildRequires : brotlipy
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : h2
BuildRequires : httpcore
BuildRequires : sniffio

%description
<p align="center">
<a href="https://www.python-httpx.org/"><img width="350" height="208" src="https://raw.githubusercontent.com/encode/httpx/master/docs/img/butterfly.png" alt='HTTPX'></a>
</p>

%package license
Summary: license components for the httpx package.
Group: Default

%description license
license components for the httpx package.


%package python
Summary: python components for the httpx package.
Group: Default
Requires: httpx-python3 = %{version}-%{release}

%description python
python components for the httpx package.


%package python3
Summary: python3 components for the httpx package.
Group: Default
Requires: python3-core
Provides: pypi(httpx)
Requires: pypi(certifi)
Requires: pypi(httpcore)
Requires: pypi(rfc3986)
Requires: pypi(sniffio)

%description python3
python3 components for the httpx package.


%prep
%setup -q -n httpx-0.17.0
cd %{_builddir}/httpx-0.17.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1614611560
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/httpx
cp %{_builddir}/httpx-0.17.0/LICENSE.md %{buildroot}/usr/share/package-licenses/httpx/bf27cf8dab26c3e420ca5578065654498f6bd496
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/httpx/bf27cf8dab26c3e420ca5578065654498f6bd496

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
