#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : httpx
Version  : 0.21.1
Release  : 20
URL      : https://files.pythonhosted.org/packages/5d/d4/739bdfb68a7dee54c795e1977abd0c81f83235499488a10717b699dab061/httpx-0.21.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/5d/d4/739bdfb68a7dee54c795e1977abd0c81f83235499488a10717b699dab061/httpx-0.21.1.tar.gz
Summary  : The next generation HTTP client.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: httpx-bin = %{version}-%{release}
Requires: httpx-license = %{version}-%{release}
Requires: httpx-python = %{version}-%{release}
Requires: httpx-python3 = %{version}-%{release}
Requires: Pygments
Requires: async_generator
Requires: brotli
Requires: certifi
Requires: charset-normalizer
Requires: click
Requires: h2
Requires: httpcore
Requires: rich
Requires: sniffio
BuildRequires : Pygments
BuildRequires : brotli
BuildRequires : buildreq-distutils3
BuildRequires : certifi
BuildRequires : charset-normalizer
BuildRequires : click
BuildRequires : h2
BuildRequires : httpcore
BuildRequires : rich
BuildRequires : sniffio

%description
<p align="center">
<a href="https://www.python-httpx.org/"><img width="350" height="208" src="https://raw.githubusercontent.com/encode/httpx/master/docs/img/butterfly.png" alt='HTTPX'></a>
</p>

%package bin
Summary: bin components for the httpx package.
Group: Binaries
Requires: httpx-license = %{version}-%{release}

%description bin
bin components for the httpx package.


%package license
Summary: license components for the httpx package.
Group: Default

%description license
license components for the httpx package.


%package python
Summary: python components for the httpx package.
Group: Default
Requires: httpx-python3 = %{version}-%{release}

%description python
python components for the httpx package.


%package python3
Summary: python3 components for the httpx package.
Group: Default
Requires: python3-core
Provides: pypi(httpx)
Requires: pypi(certifi)
Requires: pypi(charset_normalizer)
Requires: pypi(httpcore)
Requires: pypi(rfc3986)
Requires: pypi(sniffio)

%description python3
python3 components for the httpx package.


%prep
%setup -q -n httpx-0.21.1
cd %{_builddir}/httpx-0.21.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1637076672
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
pypi-dep-fix.py . httpcore
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/httpx
cp %{_builddir}/httpx-0.21.1/LICENSE.md %{buildroot}/usr/share/package-licenses/httpx/2f9a422e6ae22185bd3e9cdaec727ac95ab47bbb
python3 -tt setup.py build  install --root=%{buildroot}
pypi-dep-fix.py %{buildroot} httpcore
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/httpx

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/httpx/2f9a422e6ae22185bd3e9cdaec727ac95ab47bbb

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
